In [4]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [6]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [14]:
import numpy as np

arr = np.array(42)
arr

array(42)

In [38]:
import numpy as np

arr = np.array([1,2,3])
print(arr.ndim)

1


In [30]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])
arr


array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
import numpy as np

arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[1,2,3]]])
arr
print(arr.ndim)

3


In [58]:
arr = np.array([1,2,3],ndmin= 5)
arr
print(arr.shape)

(1, 1, 1, 1, 3)


In [34]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [52]:
import numpy as np

arr = np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
print(arr.shape)
arr

(2, 2, 3)


array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

In [ ]:
"""Given a list of numbers, find the sum of all even numbers"""


In [62]:
def sum_even_num(numbers):
    filter_numbers = [i for i in numbers if isinstance(i,int)]
    total = sum(a for a in filter_numbers if a%2==0)
    return total
b= []
sum_even_num(b)

0

In [68]:
def sum_of_even_numbers(numbers):
    
    if not numbers:  # Check if the list is empty
        return 0

    even_sum = 0
    for number in numbers:
        if isinstance(number, (int, float)): # Check if it is a number, handles potential type errors
            if number % 2 == 0:  # Check if the number is even
                even_sum += number
        else:
            print(f"Warning: Ignoring non-numeric value: {number}") #Handles non numeric values in list

    return even_sum

# Example usage:
numbers2 = [16, 13, 24, 53, 67, 70,"a","b"]
sum_of_even_numbers(numbers2)

110

In [84]:
a ="hello"
list1=list(a)
print(list1)

['h', 'e', 'l', 'l', 'o']


In [103]:
list1 = [10, 20, 30, 40,20]
list2 = [20, 40, 60, 80,20]
def find_common(a,b):
    common=[]
    for i in a:
        for j in b:
            if i==j:
              common.append(i)
    return common
find_common(list1,list2)


[20, 20, 40, 20, 20]

In [39]:
import numpy as np

arr = np.array([
    [
    [1,2,3],
    [1,2,3]
    ],
    [
    [1,2,3],
    [1,2,3]
    ],
    [
    [1,2,3],
    [1,2,3]
    ]
])
arr[0::]

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

In [45]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
"""Create a NumPy array with values from 1 to 10."""

In [51]:
import numpy as np

arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
"""Array of zeros and ones
Create a 5×5 matrix filled with zeros and another filled with ones."""

In [85]:
import numpy as np

arr = np.ones((5,5,5,5))
arr

array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1.,

In [ ]:
"""Array with a range
Create an array with values ranging from 10 to 50, with a step of 5."""

In [87]:
import numpy as np

arr = np.arange(10,50,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
"""Reshape an array
Convert a 1D array of size 9 into a 3×3 matrix."""

In [91]:
import numpy as np

arr = np.arange(0,9)
new_arr = arr.reshape(3,3)
new_arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
"""Extract elements
Given an array arr = np.array([1, 2, 3, 4, 5, 6]), extract elements greater than 3."""

In [97]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
filter_arr = arr[arr>3]
filter_arr



array([4, 5, 6])

In [ ]:
"""Reverse an array
Reverse a NumPy array without using a loop."""

In [99]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
arr[::-1]

array([6, 5, 4, 3, 2, 1])

In [ ]:
"""Extract specific elements
Given a 2D array, extract the second column."""

In [113]:
import numpy as np

arr = np.arange(1,7).reshape(2,3)
print(arr)
arr[:,1]

[[1 2 3]
 [4 5 6]]


array([2, 5])

In [ ]:
"""Set elements to zero
Given an array, set all elements greater than 10 to zero."""

In [119]:
import numpy as np

arr = np.arange(9,17)
arr[arr>10]=0
arr

array([ 9, 10,  0,  0,  0,  0,  0,  0])

In [ ]:
"""Find index positions
Given an array, find the indices where elements are greater than 5."""

In [127]:
import numpy as np

arr = np.arange(0,10)
indices = np.where(arr>5)
print(indices)

(array([6, 7, 8, 9], dtype=int64),)


In [133]:
import numpy as np

arr = np.array([1, 3, 7, 9, 2, 6, 4, 8])

# Find indices where elements are greater than 5
arr[arr>5]


array([7, 9, 6, 8])

In [ ]:
"""Element-wise operations
Given two arrays A = np.array([1, 2, 3]) and B = np.array([4, 5, 6]), compute their element-wise sum, difference, product, and quotient."""

In [139]:
import numpy as np

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
element_sum = A+B
element_dif = A-B
element_product = A*B
element_quotien =A/B
print(element_sum)
print(element_dif)
print(element_product)
print(element_quotien)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
"""Mean and Standard Deviation
Compute the mean and standard deviation of a random 3×3 matrix."""

In [147]:
import numpy as np

arr = np.arange(0,6).reshape(2,3)
print(arr.mean())
print(arr.std())

2.5
1.707825127659933


In [ ]:
"""Find min and max
Find the minimum and maximum values in an array."""

In [151]:
import numpy as np

arr = np.array([1, 3, 7, 9, 2, 6, 4, 8])
print(arr.min())
print(arr.max())


1
9


In [ ]:
"""Dot product
Compute the dot product of two matrices."""

In [161]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A)
print(B)
dot = np.dot(A,B)
dot

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[19, 22],
       [43, 50]])

In [ ]:
"""Sum along axis
Given a 3×3 matrix, compute the sum along rows and columns."""



In [167]:
import numpy as np

arr = np.arange(0,9).reshape(3,3)
colum_sum = np.sum(arr,axis=0)
colum_sum

array([ 9, 12, 15])